version: '3.9'
services:
  mysqldb:
    build: ./database
    image: mysql:5.7.26
    container_name: mysqldb
    volumes:
      - ./database/data:/var/lib/mysql:rw
    ports:
      - '3306:3306'
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
    networks:
      - nesjs-network
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sampram/todo-examp:latest
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DBNAME=${MYSQL_DBNAME}
    ports:
      - '3030:3030' # expose-to-the-world : only-in-the-docker
    container_name: todo-examp
    depends_on:
      - mysqldb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nesjs-network
volumes:
  database:
networks:
  nesjs-network:
    driver: bridge
